//! fop-pdf-renderer — Pure Rust PDF-to-image renderer
//!
//! Renders PDF pages to raster images (PNG/RGBA) without any C dependencies.
//! Designed to work with PDFs generated by fop-render, enabling self-contained
//! testing and verification.
//!
//! # Quick Start
//!
//! ```no_run
//! use fop_pdf_renderer::PdfRenderer;
//!
//! let pdf_data = std::fs::read("output.pdf").unwrap();
//! let renderer = PdfRenderer::from_bytes(&pdf_data).unwrap();
//!
//! println!("Pages: {}", renderer.page_count());
//!
//! // Render page 0 at 150 DPI
//! let image = renderer.render_page(0, 150.0).unwrap();
//!
//! // Save as PNG
//! renderer.save_as_png(0, "output.png", 150.0).unwrap();
//! ```

pub mod content;
pub mod error;
pub mod font;
pub mod graphics;
pub mod image;
pub mod parser;
pub mod rasterizer;
pub mod text;

pub use error::{PdfRenderError, Result};
pub use rasterizer::RasterPage;

/// High-level PDF renderer
///
/// Parses a PDF document and provides page rendering capabilities.
pub struct PdfRenderer {
    doc: parser::PdfDocument,
}

impl PdfRenderer {
    /// Parse a PDF document from bytes
    pub fn from_bytes(data: &[u8]) -> Result<Self> {
        let doc = parser::PdfDocument::from_bytes(data)?;
        Ok(Self { doc })
    }

    /// Number of pages in the document
    pub fn page_count(&self) -> usize {
        self.doc.page_count()
    }

    /// Render a single page at the given DPI
    ///
    /// Returns a `RasterPage` with RGBA pixels.
    pub fn render_page(&self, page_index: usize, dpi: f32) -> Result<RasterPage> {
        let page = self.doc.get_page(page_index)?;
        let mut rasterizer = rasterizer::PageRasterizer::new(&self.doc);
        rasterizer.render(&page, dpi)
    }

    /// Render a page and save it as a PNG file
    pub fn save_as_png(&self, page_index: usize, path: &str, dpi: f32) -> Result<()> {
        let page = self.render_page(page_index, dpi)?;
        page.save_png(path)
    }

    /// Render all pages and return them as PNG bytes
    pub fn render_all_pages(&self, dpi: f32) -> Result<Vec<Vec<u8>>> {
        let mut pages = Vec::new();
        for i in 0..self.page_count() {
            let page = self.render_page(i, dpi)?;
            pages.push(page.to_png()?);
        }
        Ok(pages)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_empty_pdf_returns_error() {
        let result = PdfRenderer::from_bytes(b"not a pdf");
        assert!(result.is_err());
    }

    #[test]
    fn test_minimal_pdf() {
        // A minimal valid PDF structure
        let pdf = b"%PDF-1.4\n\
            1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n\
            2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n\
            3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] >>\nendobj\n\
            xref\n0 4\n0000000000 65535 f \n0000000009 00000 n \n0000000058 00000 n \n0000000115 00000 n \n\
            trailer\n<< /Size 4 /Root 1 0 R >>\nstartxref\n200\n%%EOF\n";

        let renderer = PdfRenderer::from_bytes(pdf);
        // May succeed or fail depending on xref accuracy, but should not panic
        if let Ok(r) = renderer {
            assert_eq!(r.page_count(), 1);
        }
    }
}
